version: '3.7'
services:
  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo-db
    volumes:
      - ./db/:/data/db
  vera:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vera
    ports:
      - "8080:80"
