version: '3.7'
services:
  mongo-db:
    image: mongo:4
    container_name: mongo-db
    volumes:
      - ./docker-mounts/mongo/db/:/data/db
  vera:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: vera
    depends_on:
      - mongo-db
    environment:
      VERADB_URL: mongodb://mongo-db:27017/deploy_log
    ports:
      - "8080:80"
