version: '3.9'
services:
  mongo-db:
    image: mongo:4
    container_name: mongo-db
    volumes:
      - ./docker-mounts/mongo/db/:/data/db
    ports:
      - 27017:27017

  vera:
    build:
      context: .
      dockerfile: Dockerfile.dev
   
    depends_on:
      - mongo-db
    environment:
      VERADB_URL: mongodb://mongo-db:27017/deploy_log
    ports:
      - "8080:8080"
