#!/bin/sh
#
# chkconfig: 35 99 99
# description: Generic Nodejs init script
#

. /etc/rc.d/init.d/functions

APP_NAME=$(echo $0| cut -d'/' -f4)
USER="srvappserver"
DAEMON="nohup /usr/local/node/default/bin/node"
ROOT_DIR="/app/$APP_NAME"
SERVER="$ROOT_DIR/server.js"
LOG_FILE="$ROOT_DIR/$APP_NAME.log"
LOCK_FILE="/var/lock/subsys/$APP_NAME"
CFG_FILE="$ROOT_DIR/config.sh"

do_start() {
        if [ ! -f "$LOCK_FILE" ] ; then
                echo -n $"Starting $SERVER: "
                runuser -l "$USER" -c "cd $ROOT_DIR && . $CFG_FILE && $DAEMON $SERVER < /dev/null >> $LOG_FILE 2>&1 &" && echo_success || echo_failure
                RETVAL=$?
                echo
                [ $RETVAL -eq 0 ] && touch $LOCK_FILE
        else
                echo "$SERVER is locked."
                RETVAL=1
        fi
}

do_stop() {
        echo -n $"Stopping $SERVER: "
        pid=`ps -aefw | grep "$DAEMON $SERVER" | grep -v " grep " | awk '{print $2}'`
        kill -9 $pid > /dev/null 2>&1 && echo_success || echo_failure
        RETVAL=$?
        echo
        rm -f $LOCK_FILE || echo 'no lock file deleted'
}

case "$1" in
        start)
                do_start
                ;;
        stop)
                do_stop
                ;;
        restart)
                do_stop
                do_start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                RETVAL=1
esac

exit $RETVAL
