version: 2.1

executors:
  deployment-cli:
    docker:
      - image: navikt/deployment-cli:v0.2.0

references:
    container_config: &container_config
        docker:
            - image: circleci/node:10.9
        working_directory: ~/vera

workspace_root: &workspace_root /tmp/workspace

docker_dist: &docker_dist /tmp/docker

restore_source: &restore_source
    restore_cache:
        keys:
            - v1-repo-{{ .Branch }}-{{ .Revision }}

restore_node_modules: &restore_node_modules
    restore_cache:
        keys:
        - v1-dependencies-node-{{ checksum "package.json" }}

attach_workspace: &attach_workspace
    attach_workspace:
        at: *workspace_root

attach_docker_dist: &attach_docker_dist
    attach_workspace:
        at: *docker_dist

read_environment_variables: &read_environment_variables
    run:
        name: Set up environment variables
        command: cat /tmp/workspace/properties.env >> $BASH_ENV


jobs:
    checkout_code:
        <<: *container_config
        steps:
            - checkout
            - save_cache:
                key: v1-repo-{{ .Branch }}-{{ .Revision }}
                paths:
                    - .

    build_and_test:
        <<: *container_config
        steps:
            - *restore_source
            - run:
                name: 'Test and bundle'
                command: |
                  checkout_dir=$(pwd)
                  ls -la 
                  npm install
                  npm test  
                  mkdir -p /tmp/docker/dist
                  cp -r server.js backend /tmp/docker/dist
                  cd /tmp/docker/dist && cp ${checkout_dir}/package.json . && npm install --production && cd -
                  # getting required node_modules for production
                  npm install && node ./node_modules/gulp/bin/gulp.js dist || exit 1
                  cp -r --parents frontend/build /tmp/docker/dist
                  cp Dockerfile /tmp/docker/dist
                  ls -la /tmp/docker/dist

        #stage("build and publish docker image") {
        #    def imageName = "docker.adeo.no:5000/${application}:${releaseVersion}"
        #    sh "sudo docker build -t ${imageName} ./docker"
        #    sh "sudo docker push ${imageName}"
        #}         stage("run unit tests") {
        #    withEnv(['HTTP_PROXY=http://webproxy-utvikler.nav.no:8088', 'NO_PROXY=adeo.no']) {
        #        sh "npm install"
        #        sh "npm test"
        #    }
        #}

        #stage("build frontend bundle") {
        #    withEnv(['HTTP_PROXY=http://webproxy-utvikler.nav.no:8088', 'NO_PROXY=adeo.no']) {
        #        sh "mkdir -p ${distDir}"
        #        sh "cp -r server.js backend ${distDir}"
        #        sh "cd ${distDir} && cp ../../package.json . && npm install --production && cd -"
        #        //    getting required node_modules for production
        #        sh "npm install && node ./node_modules/gulp/bin/gulp.js dist || exit 1" // Creating frontend bundle
        #        sh "cp -r --parents frontend/build ${distDir}" // Copying frontend bundle
        #        sh "cp Dockerfile ${dockerDir}"
        #    }
        #}

        #stage("build and publish docker image") {
        #    def imageName = "docker.adeo.no:5000/${application}:${releaseVersion}"
        #    sh "sudo docker build -t ${imageName} ./docker"
        #    sh "sudo docker push ${imageName}"
        #}
            - persist_to_workspace: 
                root: *docker_dist
                paths:
                  - .

    generate_version_number:
        <<: *container_config
        steps:
        - *restore_source
        - run:
            name: 'Generate version number'
            command: |
                mkdir /tmp/workspace
                export VERSION=$(date "+%Y-%m-%d")-$(git --no-pager log -1 --pretty=%h)
                echo "export VERSION=\"$VERSION\"" >> /tmp/workspace/properties.env
        - persist_to_workspace:
            root: *workspace_root
            paths:
                - properties.env
        #- run:
        #    name: 'ls'
        #    command: |
        #        ls -la /tmp/workspace
        #        cat /tmp/workspace/properties.env

    release:
        <<: *container_config
        steps:
            - *attach_workspace
            - *read_environment_variables
            - *attach_docker_dist
            - setup_remote_docker:
                docker_layer_caching: true
            - run:
                name: Login to GPR
                command: echo "$GPR_PASSWORD" | docker login -u "$GPR_USER" --password-stdin docker.pkg.github.com
            - run:
                name: Build and push docker image
                command: |
                    ls -la /tmp/docker/dist
                    docker build -t docker.pkg.github.com/navikt/vera/vera:${VERSION} /tmp/docker/dist
                    docker push docker.pkg.github.com/navikt/vera/vera:${VERSION}
    
     
    deploy_to_dev:
        executor: deployment-cli
        steps:
            - deploy-to-nais:
                environment: dev-sbs

    deploy_to_prod:
        executor: deployment-cli
        steps:
             - deploy-to-nais:
                environment: prod-sbs

commands:
    deploy-to-nais:
        parameters:
            environment:
                type: string
        steps:
            - *attach_workspace
            - *read_environment_variables
            - checkout
            - add_ssh_keys:
                fingerprints: 
                    - '4d:b4:76:1a:3d:51:39:6f:50:e9:f6:70:14:16:88:8a'
            - run:
                name: 'Checkout aura-infra repo'
                command: git clone git@github.com:navikt/aura-infra.git

            - decrypt-private-key   
            - run:
                name: deploy to << parameters.environment >> 
                command: deployment-cli deploy create 
                    --cluster=<< parameters.environment >>  
                    --repository=navikt/basta-frontend 
                    --team aura 
                    --resource=aura-infra/templates/vera.yaml 
                    --var version=${VERSION} 
                    --appid=21324 
                    --key=github.key.pem
            - run:
                name: cleanup
                command: rm github.key.pem

    decrypt-private-key:
        steps:
            - run:
                name: "Decrypt private key"
                command: |
                    openssl aes-256-cbc -K $OPENSSL_KEY -iv $OPENSSL_IV -in aura-infra/deployment-keys/github.key.pem.enc -out github.key.pem -d
                
        
workflows:
    build_and_release:
        jobs:
            - checkout_code
            - build_and_test:
                requires:
                    - checkout_code
            - generate_version_number:
                filters:
                    branches:
                        only: master
                requires:
                    - checkout_code
            - release:
                filters:
                    branches:
                        only: master
                requires:
                    - build_and_test
                    - generate_version_number
            - deploy_to_dev:
                filters:
                    branches:
                        only: master
                requires:
                    - release
            #- deploy_to_prod:
            #    filters:
            #        branches: 
            #            only: master
            #    requires:
            #        - deploy_to_dev
