apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vera-backup
    team: aura
  name: vera-backup
  namespace: aura
spec:
  selector:
    matchLabels:
      app: vera-backup
  template:
    metadata:
      labels:
        app: vera-backup
      name: vera-backup
      namespace: aura
    spec:
      containers:
      - image: ghcr.io/nais/mongo-backup:0.1
        command: ["sleep","infinity"]
        name: vera-backup
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: gpr-credentials
      - name: ghcr-credentials
      serviceAccountName: vera-backup
#---
#apiVersion: v1
#kind: Pod
#metadata:
#  labels:
#    app: vera-backup
#  name: vera-backup
#  namespace: aura
#spec:
#  serviceAccountName: vera-backup
#  containers:
#  - image: ghcr.io/nais/mongo-backup:0.1
#    name: vera-backup
#    command: ["sleep","infinity"]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app: vera-backup
    team: aura
  name: vera-backup
  namespace: aura
spec:
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          linkerd.io/is-control-plane: "true"
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.6.0.0/15
        - 172.16.0.0/12
        - 192.168.0.0/16
  - to:
    - podSelector:
        matchLabels:
          app: vera
  - to:
    - ipBlock:
        cidr: 172.16.0.2/32
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: nais
      podSelector:
        matchLabels:
          app: prometheus
  - from:
    - namespaceSelector:
        matchLabels:
          linkerd.io/is-control-plane: "true"
  - from:
    - namespaceSelector:
        matchLabels:
          linkerd.io/extension: viz
      podSelector:
        matchLabels:
          component: tap
  - from:
    - namespaceSelector:
        matchLabels:
          linkerd.io/extension: viz
      podSelector:
        matchLabels:
          component: prometheus
  podSelector:
    matchLabels:
      app: vera-backup
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vera-backup
  namespace: aura
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: verabackupbinding
  namespace: aura
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- namespace: aura
  kind: ServiceAccount
  name: vera-backup
