apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: aura
  name: vera-backup
  namespace: aura
spec:
  activeDeadlineSeconds: 6000
  backoffLimit: 5
  failedJobsHistoryLimit: 2
  gcp:
    buckets:
      - cascadingDelete: false
        name: vera-backup-bucket
        retentionPeriodDays: 30
  image: ghcr.io/nais/mongo-backup:0.8
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
  restartPolicy: Never
  schedule: '0 */6 * * *'
  skipCaBundle: true
  successfulJobsHistoryLimit: 2
  ttlSecondsAfterFinished: 60
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app: vera-backup
    team: aura
  name: vera-backup-apiserver
  namespace: aura
spec:
  egress:
  - to:
    - ipBlock:
        cidr: 172.16.0.2/32
  podSelector:
    matchLabels:
      app: vera-backup
  policyTypes:
  - Egress
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vera-backup
  namespace: aura
rules:
  - apiGroups: [ "" ]
    resources: [ "pods/exec" ]
    verbs: [ "create" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vera-backup
  namespace: aura
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vera-backup
subjects:
- namespace: aura
  kind: ServiceAccount
  name: vera-backup
