---
apiVersion: nais.io/v1
kind: Alert
metadata:
  name: vera-alerts
  namespace: aura
  labels:
    team: aura
spec:
  receivers:
    slack:
      channel: "nais-alerts-prod"
  alerts:
    - alert: Vera is down
      expr: min(kube_pod_container_status_running{container="vera"}) < 1
      for: 5m
      description: "Vera is not running\n\nConsequence: not many.\n"
      action: "Check logs:\n- `kubectl logs -n aura $(kubectl get pod -n aura -l app=vera --no-headers -o custom-columns=\":metadata.name\") vera`\n\n2nd line: #pig_deploy @pig-deploy"
      sla: respond within office hours
      severity: danger
