apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: vera
  namespace: aura
  labels:
    team: aura
spec:
  image: {{ image }}
  port: 80
  accesspolicy:
    outbound:
      rules:
      - application: vera-mongo
  liveness:
    path: /selftest
  readiness:
    path: /selftest
  prometheus:
    path: /metrics
  replicas:
    min: 2
    max: 2
  ingresses: 
    - {{ ingress }}
  env:
    - name: VERADB_URL
      value: {{ db }}
    - name: VERADB_USERNAME
      value: "sera"
  skipCaBundle: true
  resources:
    limits:
      cpu: 500m 
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
