apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: vera
  namespace: team-atom
  labels:
    team: team-atom
spec:
  image: {{ image }}
  port: 3000
  accessPolicy:
    outbound:
      rules:
      - application: vera-mongo
  liveness:
    path: /api/isalive
  readiness:
    path: /api/selftest
  prometheus:
    path: /metrics
  replicas:
    min: 2
    max: 2
  ingresses:
  {{#each ingress }}
    - {{ this }}
  {{/each }}
  env:
    - name: VERADB_URL
      value: mongodb://vera-mongo-0.vera-mongo:27017,vera-mongo-1.vera-mongo:27017,vera-mongo-2.vera-mongo:27017/deploy_log?replicaSet=MainRepSet
  skipCaBundle: true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi


---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: {{serviceAccount}}
  labels:
    app: vera
    team: team-atom
  name: vera
  namespace: team-atom
