apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: vera
  namespace: aura
  labels:
    team: aura
spec:
  image: {{ image }}
  port: 8080
  accessPolicy:
    outbound:
      rules:
      - application: vera-mongo
    inbound:
      rules:
    {{#each access_policy_inbound_rules}}
      - application: {{app}}
        namespace: {{namespace}}
        cluster: {{cluster}}
    {{/each}}
  liveness:
    path: /selftest
  readiness:
    path: /selftest
  prometheus:
    path: /metrics
  replicas:
    min: 2
    max: 2
  ingresses:
  {{#each ingress }}
    - {{ this }}
  {{/each }}
  env:
    - name: VERADB_URL
      value: mongodb://vera-mongo-0.vera-mongo:27017,vera-mongo-1.vera-mongo:27017,vera-mongo-2.vera-mongo:27017/deploy_log?replicaSet=MainRepSet
    - name: VERADB_USERNAME
      value: "sera"
  skipCaBundle: true
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 50m
      memory: 64Mi
