---
apiVersion: v1
kind: Service
metadata:
  name: vera-mongo
  namespace: team-atom
  labels:
    name: vera-mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    role: vera-mongo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vera-mongo
  namespace: team-atom
spec:
  serviceName: vera-mongo
  replicas: 3
  selector:
    matchLabels:
      role: vera-mongo
  template:
    metadata:
      labels:
        role: vera-mongo
        environment: test
        replicaset: MainRepSet
        app: vera-mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongod-container
          image: {{ mongoimage }}
          command:
            - "mongod"
            - "--bind_ip"
            - "0.0.0.0"
            - "--replSet"
            - "MainRepSet"
          resources:
            requests:
              cpu: 0.2
              memory: 1.25Gi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: false
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-persistent-storage-claim
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-persistent-storage-claim
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "ssd-storage"
        resources:
          requests:
            storage: 1Gi
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app: vera-mongo
    team: team-atom
  name: vera-mongo
  namespace: team-atom
spec:
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              linkerd.io/is-control-plane: "true"
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              role: vera-mongo
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.6.0.0/15
              - 172.16.0.0/12
              - 192.168.0.0/16
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: nais
          podSelector:
            matchLabels:
              app: prometheus
    - from:
        - namespaceSelector:
            matchLabels:
              name: team-atom
          podSelector:
            matchLabels:
              app: vera
    - from:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              role: vera-mongo
    - from:
        - namespaceSelector:
            matchLabels:
              linkerd.io/is-control-plane: "true"
    - from:
        - namespaceSelector:
            matchLabels:
              linkerd.io/extension: viz
          podSelector:
            matchLabels:
              component: tap
    - from:
        - namespaceSelector:
            matchLabels:
              linkerd.io/extension: viz
          podSelector:
            matchLabels:
              component: prometheus
  podSelector:
    matchLabels:
      role: vera-mongo
  policyTypes:
    - Ingress
    - Egress
