name: Build vera-backup

on:
  push:
    paths:
      - 'vera-backup/**'
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: team-atom #
          docker_context: './vera-backup' # optional, default .
          dockerfile: './vera-backup/Dockerfile'
          image_suffix: 'backup'
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }} # required, but is defined as an organization variable
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }} # required, but is defined as an organization secret
      - name: Print image version
        env:
          IMAGE: ${{ steps.docker-push.outputs.image }}
        run: echo "image $IMAGE"
